### ISSUE TITLE
Invalid Access Token when retrieving patient data but after successfully getting a new token

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [dancinnamon-okta/okta-smartfhir-docs#14]
I am using Postman and I am finally able to successfully get an access token, when I click 'get new access token' in postman it open a popup window with login UI. I login and then it shows me the patient picker UI. I select a patient and then click next and proceed forward and finally postman shows it successfully obtain an access token. I save the token and use it as a bearer token to make a GET request `{{API_URL}}/Patient/:id`

the patient id in the params is whatever came prefilled in postman, I assume it is the id of one of the demo patients added `207f22d6-8b09-4310-b2da-b9076b8ee5a7`

But instead of getting back the fhir patient record I get "Invalid Access Token"

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/118219830/210631744-1ddc76fb-a32b-48c6-88b2-49f48fe616ce.png">

But I just got the token from the server, and immediately try to use it but it says invalid access token. The same thing happen for the other postman requests even the one to search patients, all of them return invalid access token. But postman successfully gets the access token so I am not sure what this is due too. 

Here are the logs for the fhir service showing the 401 error

```
{
    "authorizer.claims.sub": "-",
    "error.message": "-",
    "extendedRequestId": "eO1fCHBLvHcFjZA=",
    "httpMethod": "GET",
    "identity.sourceIp": "68.6.214.184",
    "integration.error": "-",
    "integration.integrationStatus": "200",
    "integration.latency": "35",
    "integration.requestId": "d49c36f8-5ab9-467e-bc59-b4c1f8faeff2",
    "integration.status": "401",
    "path": "/dev/Patient/207f22d6-8b09-4310-b2da-b9076b8ee5a7",
    "requestId": "e0f5c1d8-07bd-4520-b18b-324b1e7dbf1c",
    "responseLatency": "39",
    "responseLength": "367",
    "stage": "dev",
    "status": "401"
}
```

I am not sure what I am doing wrong here but it seems like I get a new access token and the fhir server thinks its invalid because its not checking the token with the right idp? I am not sure what do you think? Any help is greatly appreciated thank you!

**Comment by feroze-shahpurwala-visiontree** [comment]
```
2023-01-05T04:01:58.571Z	ERROR	UnauthorizedError: Invalid access token
    at decodeJwtToken (/var/task/src/index.js:116952:15)
    at verifyJwtToken (/var/task/src/index.js:116958:32)
    at SMARTHandler.verifyAccessToken (/var/task/src/index.js:116573:80)
    at /var/task/src/index.js:128302:75
    at Layer.handle [as handle_request] (/var/task/src/index.js:125691:5)
    at trim_prefix (/var/task/src/index.js:125012:13)
    at /var/task/src/index.js:124970:9
    at Function.process_params (/var/task/src/index.js:125030:12)
    at next (/var/task/src/index.js:124964:10)
    at setContentTypeMiddleware (/var/task/src/index.js:141488:9) {
  isUnauthorizedError: true
  ```

**Comment by dancinnamon-okta** [comment]
Yeah that's correct- the FHIR service essentially needs to be configured to trust the tokens that you're sending along.  Which FHIR service are you using?

**Comment by feroze-shahpurwala-visiontree** [comment]
AWS Fhir Works which then recommended the Okta Smart Auth Framework - https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline

I am using the smart-mainline deployment too. 

issuer - https://dev-XXXXXXXX.okta.com/oauth2/default

OAuth2 API - ttps://dev-XXXXXXXX.okta.com/oauth2/default/

patientPicker Endpoint - https://abcdefghi.execute-api.us-west-2.amazonaws.com/dev

I deployed with those endpoint as properties. I thought it should be connected with that and I can't seem to narrow in on why its not working with the logs.

**Comment by dancinnamon-okta** [comment]
Ok great- I figured that might be but wanted to be sure.  There's really 2 things that could be going on:
1- It doesn't like the signature, issuer or audience of the token.  It seems like you have that configured correctly though.
2- You don't have the proper scopes requested, or the proper patient id claim isn't in the token.

Can you take your access token, paste it into https://jwt.io, and then post the decoded output here? I can take a look at it and see if I see anything unexpected. There could be a patient ID in the token, so if there is,  please abstract that!

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta here is the decoded output

```
{
  "ver": 1,
  "jti": "AT.-Y5vMg5GNWtdYbDxUBRTJrtFWRIM8NeIc0G-Iplz7Uo",
  "iss": "https://dev-51546937.okta.com/oauth2/default",
  "aud": "https://https://y8a36jamwj.execute-api.us-west-2.amazonaws.com/dev",
  "iat": 1672942718,
  "exp": 1672946318,
  "cid": "0oa7np1kcyGGtfbvq5d7",
  "uid": "00u7jqg7vgStkWbn35d7",
  "scp": [
    "fhirUser",
    "patient/*.*",
    "launch/patient",
    "user/*.*",
    "patient_selection",
    "openid",
    "profile"
  ],
  "auth_time": 1672942555,
  "sub": "fshahpurwala@visiontree.com",
  "launch_response_patient": "3758",
  "valid_consent": "true",
  "fhirUser": "Patient/null"
}
```

is it the fhirUser type?

**Comment by feroze-shahpurwala-visiontree** [comment]
I am guessing it is the fhirUser type being 'Patient/null' seems incorrect. I have to investigate why is it sending that parameter as the fhir user.

**Comment by dancinnamon-okta** [comment]
Oh nice- so yeah i actually don't think that's it (although I agree that's not what it should be).  I think more likely it's the value of "launch_response_patient".  The authorization within fhirWorks does look at that value and ensure that you're only requesting data related to that patient (as it should if you have a patient/* scope).
The "3758" value is a faked-out patient ID that exists in the public hapi.fhir.org server.  I have it hard-coded in the mock-patient-service.js file.  For testing purposes, you should take the full FHIR URL of a real patient in your FHIR server, and update that file with that value.  So the value of launch_response_patient should be something like: https://https://y8a36jamwj.execute-api.us-west-2.amazonaws.com/dev/Patient/XXXX

**Comment by feroze-shahpurwala-visiontree** [comment]
`"launch_response_patient": "3758",` 

that parameter right now is just a number, are you saying that instead of the number it should be a full url  like

`https://y8a36jamwj.execute-api.us-west-2.amazonaws.com/dev/Patient/XXXX](https://https//y8a36jamwj.execute-api.us-west-2.amazonaws.com/dev/Patient/XXXX` 

and replace the XXXX with a real patient_id from the fhir server?

**Comment by dancinnamon-okta** [comment]
Yes that's correct.

**Comment by feroze-shahpurwala-visiontree** [comment]
currently the only data I have in the fhir-works server that I setup is the demo data that came with the server. 

taking a look at the mock patient js file

```
// Mock patient access service.
// Just returns a list of sample patients for display in the custom consent patient picker.
// In a real implementation, this service would make an API call to an internal fine grained authorization service.
module.exports.mockPatientServiceHandler = async () => {
	return [
		//From Okta test set
		{patient_id: '3758', patient_name: 'Abraham Murphy (32)'},
		{patient_id: '35128', patient_name: 'Carlos Stehr (54)'},
		{patient_id: '5050', patient_name: 'Albert Walter (Deceased)'}

		//From hapi.fhir.org test set
		//{patient_id: '1440422', patient_name: 'Samuel Ortiz (31)'},
		//{patient_id: '92e12467-e074-4349-a6d4-e88be191b39b', patient_name: 'Amberly Bahringer (65)'},
		//{patient_id: 'c769110f-4d4e-4375-a706-c5d78f729544', patient_name: 'Jann Ferry (63)'}

		//From aws test set
		//{patient_id: 'Patient/57ca5687-e198-4b36-9a44-e9460debc611', patient_name: 'Sherlock Holmes (31) (reference)'},
		//{patient_id: 'https://yourFHIRserver.com/Patient/81f65d61-8f91-4472-b668-0efc0aceb0f2', patient_name: 'Mycroft Holmes (38) (full url)'},
		//{patient_id: 'Patient/7f344d58-113d-45aa-88cf-c74d8e925d1d', patient_name: 'John Watson (34) (reference)'},
		//{patient_id: 'https://fake.ehr.com/Patient/external', patient_name: '	Sir Arthur Conan Doyle (68) (external patient)'},
	]
}
```

I can see that there are different patients for okta and aws fhir-works. 

But that confuses me because I thought Okta smart auth shows a patient picker with patients from the fhir server? Then you select which patient you want to access the record and it gives you a token to access that patient. 

So whichever patients shows in the patient picker, they should exist on the fhir server is that correct or no? 

From the mock file it seems like different mock patient data with different IDs are in Okta and in the Fhir-works server though is that correct? But the patient_id in okta should correspond to the patient_id for the record in the fhir server yes? 

My goal is to have this all working as a proof of concept first by requesting a token, using the patient picker, then use the token to get the patient record from the fhir server is the goal using the test data for now. 

I am very close just need to connect these last few pieces. How do you recommend proceeding, should I edit the file above changing the `patient_id:` to the full url you mentioned above for testing purposes and deploy? 

I am confused though, shouldn't the patient picker show the patients that exist in the fhir server? If not then where does Okta store a list of patience and those patientID need to be kept in sync with fhir server? 

I don't understand how that could work, I thought Okta will retrieve the list of patience from the fhir server, and ask you which record you want access too in the patient picker? Provided that the account you are logging in from has authorization to access any patient record like a physician.

**Comment by feroze-shahpurwala-visiontree** [comment]
Actually I see that the patient is also a user with the role of patient and so Okta knows all the users that are patients without having to query the fhir server. that is how the patient picker works. 

now I have to align the patients in Okta, and the patients in the Fhir server so it is all cohesive with the correct patient Ids. 

also it seems like the patient_id must be kept in sync between Okta and the Fhir server

Okta should have all the corresponding patient_id's of all patients that exist on the fhir server correct? Otherwise Okta will not be able to grant access to a patient_id that exists in the fhir server but not associated with any user in Okta

**Comment by feroze-shahpurwala-visiontree** [comment]
Ok I fixed couple things and now trying to make a POST request to create a new patient on the fhir server and I don't get invalid access token anymore which is good but I get a new error:

`Requester's identity is in the incorrect format`

not sure what it is referring to?

**Comment by feroze-shahpurwala-visiontree** [comment]
> Ok I fixed couple things and now trying to make a POST request to create a new patient on the fhir server and I don't get invalid access token anymore which is good but I get a new error:
> 
> `Requester's identity is in the incorrect format`
> 
> not sure what it is referring to?

It is related to this open github issue https://github.com/oktadev/okta-smartfhir-docs/issues/9

**Comment by dancinnamon-okta** [comment]
Hey- Just wanted to respond to some of your comments on here to hopefully provide clarity.  By the way, I do believe the error you're having now is related to item #1.

There are really 2 identities at play here:
1- The fhirUser attribute.  This is most definitely the person at the screen logging in.  This user will always be within Okta, and it'd be recommended to have the user's fhirUser ID as an Okta profile attribute (that was the intention of the "patient_id" attribute from the instructions).  Depending upon your architecture, this would likely just be filled out as part of the registration process when the user creates their new account (the registration process would need to do a match of some sort, and fill in the fhirUser attribute on the user's Okta profile when creating. 
The actual value of this can vary based on your architecture- it could be a patient ID, a practitioner ID, Person ID etc.  
Note: I would like to update the setup instructions, because the setup instructions assume the user is a "patient", so that's why I call the attribute "patient_id" when that's not necessarily accurate for everyone.

2- The patient selected on the patient picker.  These IDs are not necessarily within Okta. For example, you could have access to a newborn infant patient record.  That newborn infant will not have a user within Okta.  The intention is that, instead of calling the "mock patient service" that you make a real FHIR call, look-up in a real database, etc- the patients the user has access to and display them on the screen.

So I hope that clarifies things a little.  Since I've written the instructions I've definitely learned some new things about the format of the fields- so I am in an effort right now to update this repository to help clarify some of these things.

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta this made sense thank you

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta Hey I deployed the project using the new automated script and it works nicely. Although I am glad I went through the manual setup initially to learn how everything works, but now if I need to redeploy it is really nice to have that script it makes things a lot easier. 

I do have a question though. I have everything working so far integrating Smart Auth with the Fhir Works on AWS server. But now I want to replace the mock_patient_service with the real API call to the Fhir server. 

But I am confused about how that call is made from within the Smart server itself. I can use http fetch to make the call to the fhir server {{API_URL}}/Patient route but what about authorization, the Fhir server is likely to just reject the request isn't it? Any advice on more specifically how to make the fetch request and what properties need to be included in the request to make it work?

**Comment by dancinnamon-okta** [comment]
Awesome- thanks for the feedback on the automated script! I can definitely see a "chicken/egg" issue here because we need patient data... in the middle of authorizing to get patient data.

A few options for you:
1- You could have a "backend" FHIR API that is purpose built for this use case, and this could trust the normal OAuth2 token minted for the patient picker app.  The OAuth2 access token that is minted for the patient picker is a full-blown access token complete with user context- but it only currently has a few default openid connect scopes (openid, email, profile).  
A minor variation of this is perhaps you don't have a "backend" API, but instead you could add an additional scope to the patient picker access token, and have special treatment in the FHIRWorks SMART authorizer to allow it to make a very narrow set of FHIR queries.

2- You could set up a client_credentials flow application in Okta, and create/allow the system/Patient.read scope on that.  The patient picker app could then request that token as a "machine to machine" token that it could use to invoke the existing AWS FHIRWorks FHIR API when pulling the patient list.

3- You could bypass FHIR altogether, and have the patient picker connect directly to some backend database to get this data.

Would be great to hear your thoughts on this!

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta 

When I updated the code to try and make API call from patient picker everything broke. And then I reverted back and I get this error

(db0bec11-aabe-4cf6-acdc-056d0f19a24d) Endpoint response body before transformations: {
    "errorType": "TypeError",
    "errorMessage": "Signed cookie string must be provided.",
    "trace": [
        "TypeError: Signed cookie string must be provided.",
        "    at Object.exports.unsign (/var/task/node_modules/cookie-signature/index.js:37:39)",
        "    at Object.module.exports.getHandler (/var/task/lib/patient_picker.js:21:36)",
        "    at Runtime.module.exports.patientPickerGetHandler [as handler] (/var/task/aws/patient_picker.js:5:41)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

It is so hard to keep this running. Maybe it is me but way to fragile

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta I deleted and redeployed the entire instance followed all the setup and I am still getting

(db0bec11-aabe-4cf6-acdc-056d0f19a24d) Endpoint response body before transformations: {
    "errorType": "TypeError",
    "errorMessage": "Signed cookie string must be provided.",
    "trace": [
        "TypeError: Signed cookie string must be provided.",
        "    at Object.exports.unsign (/var/task/node_modules/cookie-signature/index.js:37:39)",
        "    at Object.module.exports.getHandler (/var/task/lib/patient_picker.js:21:36)",
        "    at Runtime.module.exports.patientPickerGetHandler [as handler] (/var/task/aws/patient_picker.js:5:41)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

This is bad, I have no idea what this error is, no way to fix it no insight just totally blocked

**Comment by feroze-shahpurwala-visiontree** [comment]
This is the cookie value in the request. How did it get so messed up just by running serverless deploy again?

t=default; DT=DI1wiwllI3QQTCSpOdxKIZhzQ; enduser_version=2; okta_user_lang=en; pickerAuthzState=null; origRequest=null; okta-oauth-redirect-params={"responseType":"code","state":"Ruks7Qz0BZ8i7Zb72XQ5fdAx80fQZ6hJPqIxPi4xY2altdyl0hA2F2Y4GnA8pExI","nonce":"n9bYRD1sraN9Oh6HeBUTkCenjhGAOZ3KwhCbxN1KsLylgC10IbJ2So400cFZPYMn","scopes":["openid","profile","email","okta.users.read.self","okta.users.manage.self","okta.internal.enduser.read","okta.internal.enduser.manage"],"clientId":"okta.2b1959c8-bcc0-56eb-a589-cfcfb7422f26","urls":{"issuer":"https://smartauth.visiontree.ninja","authorizeUrl":"https://smartauth.visiontree.ninja/oauth2/v1/authorize","userinfoUrl":"https://smartauth.visiontree.ninja/oauth2/v1/userinfo","tokenUrl":"https://smartauth.visiontree.ninja/oauth2/v1/token","revokeUrl":"https://smartauth.visiontree.ninja/oauth2/v1/revoke","logoutUrl":"https://smartauth.visiontree.ninja/oauth2/v1/logout"},"ignoreSignature":false}; okta-oauth-nonce=n9bYRD1sraN9Oh6HeBUTkCenjhGAOZ3KwhCbxN1KsLylgC10IbJ2So400cFZPYMn; okta-oauth-state=Ruks7Qz0BZ8i7Zb72XQ5fdAx80fQZ6hJPqIxPi4xY2altdyl0hA2F2Y4GnA8pExI; JSESSIONID=809372A577540E0C56062296C08EA468

**Comment by feroze-shahpurwala-visiontree** [comment]
I deleted the entire deployment and redeployed and get the same error. wow, i had it all working and now i can for the life of me get it to work anymore. It is done, i have no idea what to do

**Comment by dancinnamon-okta** [comment]
Hey @feroze-shahpurwala-visiontree 
I apologize for the delay here- I was out of the office last week.
I'm sorry you've run into issues... I was looking at your cookie header text, and it looks like both the "pickerAuthzState=null; origRequest=null;"- these are the 2 cookies that the patient picker are looking for- and it's not finding them.  Those are the cookies I'm using to determine what the original OAuth2 request is so I can render the list of scopes for approval. Somehow they're either getting lost, or not getting set to begin with.  FYI- I have heard of organizations using a database to persist these values instead of signed cookies.... this was just my attempt at reducing as much infrastructure as possible- admittedly cookies are not the easiest to debug sometimes.

I had run into this issue a couple of times a while back, and it was due to this line here: https://github.com/oktadev/okta-smartfhir-demo/blob/014ebc3c80215ae19dc0a9f73565c4215a5cbbb4/aws/authorize.js#L17

I originally didn't have the "path=/" piece in there, and it was causing my browser to drop the cookies, and hence this error was cropping up for me.

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta no worries I was just in frustrated mood don't mind me :) But I figured out the issue was overall that the patient authorization proxy doesn't work for some reason. Like what I try to use it Okta immediately redirects to 404. And so I am not sure why because I examined and everything seems to be setup ok its just that the proxy just doesn't work. And you kind of need the proxy because the authorize endpoint it /v1/smart/authorize while the token url is without the /smart/ and so you can't really enter a base oauth2 url to run the https://inferno.healthit.gov/ tests. So I modified the .well-known/smart-configuiration endpoint to have a hardcoded authorize and token endpoint. Eventually I would like to figure out why the patient_authorization proxy is not working. I have a feeling it might have something to do with Okta not recognizing the proxy and displaying a 404 or something because of the custom domain. Just a hunch but not really sure.
